// ============================================================================
// Transcript Parser - Fetch & Parse YouTube Transcript XML
// ============================================================================
//
// File này chạy trong Service Worker (Background Script).
//
// ── TẠI SAO FETCH Ở ĐÂY? ─────────────────────────────────────────────────
//
// Content Script bị CORS restriction: trình duyệt chặn cross-origin requests
// từ content scripts (dù URL thuộc youtube.com, content script context khác
// page context).
//
// Service Worker (Background) KHÔNG bị CORS khi có host_permissions phù hợp
// trong manifest.json:
//   "host_permissions": ["*://*.youtube.com/*"]
//
// → Fetch transcript XML ở đây là cách an toàn và chính xác nhất.
//
// ── YOUTUBE TIMEDTEXT XML FORMAT ──────────────────────────────────────────
//
// YouTube trả transcript dưới dạng XML từ endpoint:
//   https://www.youtube.com/api/timedtext?v=VIDEO_ID&lang=en&...
//
// Format XML:
//   <?xml version="1.0" encoding="utf-8" ?>
//   <transcript>
//     <text start="0.21" dur="3.24">Hello and welcome</text>
//     <text start="3.45" dur="2.1">to this &amp; video</text>
//   </transcript>
//
// Lưu ý:
// - Text content có thể chứa HTML entities (&amp; &lt; &gt; etc.)
// - Một số text có thể chứa line breaks (\n)
// - `start` và `dur` là số thực (floating point) tính bằng giây
// - Nếu thêm `&fmt=json3` vào URL, YouTube trả JSON thay vì XML
//
// ========================================================================

import type { TranscriptSegment, TranscriptData } from '../types/transcript';

const LOG_PREFIX = '[ChiHaiDaiCa][TranscriptParser]';

/**
 * Fetch transcript từ YouTube API và parse thành mảng TranscriptSegment.
 *
 * @param baseUrl - URL lấy từ captionTrack.baseUrl
 * @param videoId - Video ID để gắn vào kết quả
 * @param languageCode - Mã ngôn ngữ
 * @param languageName - Tên ngôn ngữ hiển thị
 * @param isAutoGenerated - Track có phải auto-generated không
 * @returns TranscriptData object hoặc throw Error
 */
/**
 * Type cho custom fetch function.
 * Cho phép Content Script cung cấp fetcher riêng (Main World injection)
 * thay vì dùng global fetch() (không có cookies YouTube).
 */
export type TextFetcher = (url: string) => Promise<{ text: string; contentType: string }>;

/**
 * Default fetcher: sử dụng global fetch().
 * Hoạt động trong Service Worker (với host_permissions)
 * nhưng KHÔNG có cookies YouTube → chỉ dùng cho fallback.
 */
const defaultFetcher: TextFetcher = async (url: string) => {
  const response = await fetch(url, {
    method: 'GET',
    headers: { 'Accept-Language': 'en-US,en;q=0.9' },
  });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }
  return {
    text: await response.text(),
    contentType: response.headers.get('content-type') || '',
  };
};

export async function fetchAndParseTranscript(
  baseUrl: string,
  videoId: string,
  languageCode: string,
  languageName: string,
  isAutoGenerated: boolean,
  fetcher: TextFetcher = defaultFetcher
): Promise<TranscriptData> {
  console.log(`${LOG_PREFIX} 📥 Fetching transcript: ${languageName} (${languageCode})`);

  // Đảm bảo URL sử dụng định dạng JSON3 (dễ parse và ổn định nhất)
  const json3Url = baseUrl.includes('fmt=json3') ? baseUrl : appendParam(baseUrl, 'fmt', 'json3');
  const segments = await tryFetchAndParse(json3Url, 'JSON3', fetcher);

  console.log(`${LOG_PREFIX} ✅ Kết quả cuối: ${segments.length} segments`);

  if (segments.length > 0) {
    console.log(`${LOG_PREFIX}    First: "${segments[0].text}" @ ${segments[0].startTime}s`);
    console.log(`${LOG_PREFIX}    Last: "${segments[segments.length - 1].text}" @ ${segments[segments.length - 1].startTime}s`);
  }

  return {
    videoId,
    segments,
    languageCode,
    languageName,
    isAutoGenerated,
    fetchedAt: Date.now(),
  };
}

/**
 * Thử fetch và parse transcript từ một URL cụ thể.
 * Sử dụng custom fetcher nếu được cung cấp.
 */
async function tryFetchAndParse(
  url: string,
  formatLabel: string,
  fetcher: TextFetcher
): Promise<TranscriptSegment[]> {
  try {
    console.log(`${LOG_PREFIX}    [${formatLabel}] Fetching: ${url.substring(0, 120)}...`);

    const { text: responseText, contentType } = await fetcher(url);

    console.log(`[Raw SW Response]:`, responseText.substring(0, 500));

    // Debug: log response info
    console.log(`${LOG_PREFIX}    [${formatLabel}] Content-Type: ${contentType}`);
    console.log(`${LOG_PREFIX}    [${formatLabel}] Response length: ${responseText.length} chars`);
    console.log(`${LOG_PREFIX}    [${formatLabel}] First 200 chars: ${responseText.substring(0, 200)}`);

    if (responseText.length === 0) {
      console.warn(`${LOG_PREFIX}    [${formatLabel}] Response rỗng!`);
      return [];
    }

    // Detect format và parse
    let segments: TranscriptSegment[];

    if (contentType.includes('application/json') || responseText.trimStart().startsWith('{')) {
      segments = parseJson3Transcript(responseText);
    } else {
      segments = parseXmlTranscript(responseText);
    }

    console.log(`${LOG_PREFIX}    [${formatLabel}] Parsed: ${segments.length} segments`);
    return segments;

  } catch (error) {
    console.warn(`${LOG_PREFIX}    [${formatLabel}] Error:`, error);
    return [];
  }
}

// ============================================================================
// URL Builder
// ============================================================================

/**
 * Thêm query parameter vào URL.
 */
function appendParam(baseUrl: string, key: string, value: string): string {
  try {
    const url = new URL(baseUrl);
    url.searchParams.set(key, value);
    return url.toString();
  } catch {
    const separator = baseUrl.includes('?') ? '&' : '?';
    return `${baseUrl}${separator}${key}=${value}`;
  }
}

// ============================================================================
// JSON3 Parser
// ============================================================================
//
// YouTube JSON3 format:
// {
//   "events": [
//     {
//       "tStartMs": 210,        // start time in milliseconds
//       "dDurationMs": 3240,    // duration in milliseconds
//       "segs": [               // segments (có thể nhiều word segments)
//         { "utf8": "Hello " },
//         { "utf8": "world" }
//       ]
//     },
//     ...
//   ]
// }
//
// Đặc biệt:
// - Thời gian tính bằng MILLISECONDS (không phải giây như XML)
// - Một event có thể có nhiều segs (word-level segments)
// - Event đầu tiên thường là metadata (không có segs) → cần filter
// ============================================================================

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string; acAsrConf?: number }>;
  // Các fields metadata (bỏ qua)
  wWinId?: number;
  wsWinStyleId?: number;
}

interface Json3Response {
  events?: Json3Event[];
}

function parseJson3Transcript(jsonText: string): TranscriptSegment[] {
  const data = JSON.parse(jsonText) as Json3Response;

  if (!data.events || !Array.isArray(data.events)) {
    console.warn(`${LOG_PREFIX} JSON3 response không có events[]`);
    return [];
  }

  const segments: TranscriptSegment[] = [];

  for (const event of data.events) {
    // Skip events không có text segments (metadata events)
    if (!event.segs || event.segs.length === 0) continue;

    // Skip events không có timing info
    if (typeof event.tStartMs !== 'number') continue;

    // Ghép các từ lại thành 1 câu hoàn chỉnh (bỏ qua ký tự xuống dòng dư thừa)
    let textSegment = '';
    event.segs.forEach(seg => {
      if (seg.utf8 && seg.utf8 !== '\n') {
        textSegment += seg.utf8;
      }
    });
    textSegment = textSegment.trim();

    // Skip segments rỗng hoặc chỉ có whitespace/newline
    if (!textSegment) continue;

    const startTime = event.tStartMs / 1000; // ms → seconds
    const duration = (event.dDurationMs || 0) / 1000;

    segments.push({
      text: decodeHtmlEntities(textSegment),
      startTime,
      duration,
      endTime: startTime + duration,
    });
  }

  return segments;
}

// ============================================================================
// XML Parser
// ============================================================================
//
// YouTube XML format (fallback nếu JSON3 không hoạt động):
//
//   <transcript>
//     <text start="0.21" dur="3.24">Hello and welcome</text>
//     <text start="3.45" dur="2.1">to this &amp; video</text>
//   </transcript>
//
// Lưu ý:
// - Service Worker KHÔNG có DOMParser API (vì không có DOM)
// - Phải parse XML bằng regex thay vì DOM parsing
// ============================================================================

function parseXmlTranscript(xmlText: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];

  // ── Format 1: Legacy <text> elements ────────────────────────────────
  // <text start="0.21" dur="3.24">Hello and welcome</text>
  const textRegex = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;

  let match: RegExpExecArray | null;
  while ((match = textRegex.exec(xmlText)) !== null) {
    const startTime = parseFloat(match[1]);
    const duration = parseFloat(match[2]);
    const rawText = match[3];

    const text = decodeHtmlEntities(rawText).trim();
    if (!text) continue;

    segments.push({
      text,
      startTime,
      duration,
      endTime: startTime + duration,
    });
  }

  // ── Format 2: SRV3 <p> elements (YouTube mới) ──────────────────────
  // <p t="210" d="3240">Hello and welcome</p>
  // Lưu ý: t và d ở đây tính bằng MILLISECONDS
  if (segments.length === 0) {
    const pRegex = /<p\s+t="([^"]+)"\s+d="([^"]+)"[^>]*>([\s\S]*?)<\/p>/g;

    while ((match = pRegex.exec(xmlText)) !== null) {
      const startTimeMs = parseInt(match[1], 10);
      const durationMs = parseInt(match[2], 10);
      const rawText = match[3]
        .replace(/<[^>]*>/g, '') // Strip inner HTML tags (<s>, etc.)
        .trim();

      const text = decodeHtmlEntities(rawText).trim();
      if (!text) continue;

      const startTime = startTimeMs / 1000;
      const duration = durationMs / 1000;

      segments.push({
        text,
        startTime,
        duration,
        endTime: startTime + duration,
      });
    }
  }

  return segments;
}

// ============================================================================
// Utility: Decode HTML Entities
// ============================================================================
//
// YouTube transcript chứa HTML entities trong text:
//   &amp;  → &
//   &lt;   → <
//   &gt;   → >
//   &quot; → "
//   &#39;  → '
//   &apos; → '
//   &#NUMBER; → Unicode character
//
// Service Worker không có DOMParser, nên phải decode thủ công.
// ============================================================================

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_match, numStr) => {
      return String.fromCharCode(parseInt(numStr, 10));
    })
    .replace(/&#x([0-9A-Fa-f]+);/g, (_match, hexStr) => {
      return String.fromCharCode(parseInt(hexStr, 16));
    })
    // Clean up line breaks thừa
    .replace(/\n/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
