// ============================================================================
// Message Types - Giao tiếp giữa Content Script ↔ Service Worker
// ============================================================================
// Tất cả messages được gửi qua chrome.runtime.sendMessage() phải tuân theo
// interface này để đảm bảo type safety xuyên suốt extension.

import type { CaptionTrack, TranscriptData } from './transcript';

/**
 * Enum định nghĩa tất cả các loại message trong hệ thống.
 * Mỗi Phase mới sẽ bổ sung thêm message types vào đây.
 */
export enum MessageType {
  // ── Phase 1: Kết nối DOM ──────────────────────────────────────────────
  /** Content Script phát hiện được thẻ <video> trên trang */
  VIDEO_DETECTED = 'VIDEO_DETECTED',

  /** Cập nhật thời gian hiện tại của video (dùng cho subtitle sync) */
  VIDEO_TIME_UPDATE = 'VIDEO_TIME_UPDATE',

  /** YouTube SPA đã navigate sang trang/video mới */
  NAVIGATION_CHANGED = 'NAVIGATION_CHANGED',

  /** Phản hồi xác nhận từ Service Worker */
  ACKNOWLEDGE = 'ACKNOWLEDGE',

  // ── Phase 2: Transcript Extraction ──────────────────────────────────
  /** Content Script trích xuất được caption tracks từ page context */
  CAPTION_TRACKS_EXTRACTED = 'CAPTION_TRACKS_EXTRACTED',

  /** Content Script yêu cầu Service Worker fetch transcript XML */
  FETCH_TRANSCRIPT = 'FETCH_TRANSCRIPT',

  /** Service Worker trả kết quả transcript đã parse */
  TRANSCRIPT_RESULT = 'TRANSCRIPT_RESULT',

  // ── Phase 3: Main World Fetch ───────────────────────────────────────
  /** Content Script yêu cầu SW fetch URL trong Main World (bypass CSP) */
  MAIN_WORLD_FETCH = 'MAIN_WORLD_FETCH',
}

// ── Message Payloads ──────────────────────────────────────────────────────

export interface VideoDetectedPayload {
  /** URL của video YouTube hiện tại */
  videoUrl: string;
  /** Video ID trích từ URL (e.g., "dQw4w9WgXcQ") */
  videoId: string;
  /** Tiêu đề video (nếu lấy được) */
  title: string;
}

export interface VideoTimeUpdatePayload {
  /** Thời gian hiện tại tính bằng giây (e.g., 125.437) */
  currentTime: number;
  /** Tổng thời lượng video tính bằng giây */
  duration: number;
  /** Video ID để identify video nào đang phát */
  videoId: string;
}

export interface NavigationChangedPayload {
  /** URL mới sau khi navigate */
  newUrl: string;
  /** URL cũ trước khi navigate */
  oldUrl: string;
}

// ── Phase 2 Payloads ──────────────────────────────────────────────────────

export interface CaptionTracksExtractedPayload {
  /** Video ID */
  videoId: string;
  /** Danh sách caption tracks có sẵn */
  tracks: CaptionTrack[];
}

export interface FetchTranscriptPayload {
  /** Video ID */
  videoId: string;
  /** URL để fetch transcript XML */
  baseUrl: string;
  /** Mã ngôn ngữ */
  languageCode: string;
  /** Tên ngôn ngữ */
  languageName: string;
  /** Có phải auto-generated không */
  isAutoGenerated: boolean;
}

export interface TranscriptResultPayload {
  /** true nếu fetch thành công */
  success: boolean;
  /** Dữ liệu transcript đã parse (nếu thành công) */
  data?: TranscriptData;
  /** Thông báo lỗi (nếu thất bại) */
  error?: string;
}

// ── Phase 3: Main World Fetch Payloads ────────────────────────────────────

export interface MainWorldFetchPayload {
  /** URL cần fetch trong Main World */
  url: string;
}

export interface MainWorldFetchResponse {
  /** true nếu fetch thành công */
  success: boolean;
  /** Nội dung text của response */
  text?: string;
  /** Content-Type header */
  contentType?: string;
  /** HTTP status code */
  status?: number;
  /** Thông báo lỗi */
  error?: string;
}

// ── Unified Message Interface ─────────────────────────────────────────────

export interface ExtensionMessage<T = unknown> {
  type: MessageType;
  payload: T;
  /** Timestamp khi message được tạo */
  timestamp: number;
}

// ── Factory Functions ─────────────────────────────────────────────────────
// Sử dụng factory functions thay vì trực tiếp tạo object để đảm bảo
// tất cả messages đều có đầy đủ fields và đúng type.

export function createMessage<T>(
  type: MessageType,
  payload: T
): ExtensionMessage<T> {
  return {
    type,
    payload,
    timestamp: Date.now(),
  };
}
