// ============================================================================
// Transcript Types - Cấu trúc dữ liệu phụ đề YouTube
// ============================================================================

/**
 * Một đoạn phụ đề (subtitle segment) với thông tin thời gian.
 *
 * Ví dụ YouTube Transcript XML:
 *   <text start="12.56" dur="3.2">Hello and welcome to this video</text>
 *
 * Sẽ được parse thành:
 *   { text: "Hello and welcome to this video", startTime: 12.56, duration: 3.2, endTime: 15.76 }
 */
export interface TranscriptSegment {
  /** Nội dung text của đoạn phụ đề (đã decode HTML entities) */
  text: string;

  /** Thời điểm bắt đầu hiển thị (giây) */
  startTime: number;

  /** Thời lượng hiển thị (giây) */
  duration: number;

  /** Thời điểm kết thúc hiển thị (giây) = startTime + duration */
  endTime: number;
}

/**
 * Thông tin một track phụ đề (một ngôn ngữ).
 *
 * YouTube cho phép video có nhiều caption tracks:
 * - Phụ đề do người tạo upload (manual)
 * - Phụ đề tự động (auto-generated) bởi YouTube ASR
 *
 * Dữ liệu này lấy từ:
 *   ytInitialPlayerResponse.captions.playerCaptionsTracklistRenderer.captionTracks[]
 */
export interface CaptionTrack {
  /** URL để fetch XML transcript, ví dụ: "https://www.youtube.com/api/timedtext?..." */
  baseUrl: string;

  /** Mã ngôn ngữ ISO 639-1, ví dụ: "en", "vi", "ja" */
  languageCode: string;

  /** Tên ngôn ngữ hiển thị, ví dụ: "English", "Tiếng Việt" */
  languageName: string;

  /** Loại track: có phải auto-generated bởi YouTube ASR không */
  kind: 'asr' | 'manual' | '';

  /** true nếu đây là phụ đề tự động (kind === 'asr') */
  isAutoGenerated: boolean;
}

/**
 * Kết quả trích xuất transcript hoàn chỉnh cho một video.
 */
export interface TranscriptData {
  /** Video ID của YouTube */
  videoId: string;

  /** Danh sách segments đã parse */
  segments: TranscriptSegment[];

  /** Ngôn ngữ của transcript này */
  languageCode: string;

  /** Tên ngôn ngữ hiển thị */
  languageName: string;

  /** Transcript này có phải auto-generated không */
  isAutoGenerated: boolean;

  /** Timestamp khi fetch xong (để cache invalidation) */
  fetchedAt: number;
}

/**
 * Danh sách tất cả caption tracks có sẵn cho một video.
 * Content Script gửi data này lên Service Worker để fetch transcript.
 */
export interface AvailableCaptions {
  /** Video ID */
  videoId: string;

  /** Danh sách tất cả caption tracks có sẵn */
  tracks: CaptionTrack[];
}
